#lark config file

Title = "lark"
Version = "0.1"
Author = "lark.im"

Debug = false

[redis]
host = "127.0.0.1"
port = 6379
db = 0
password = ""

#防止爬虫
[robot]
robot_regex: $^|trivial|facebook|MetaURI|butterfly|google|amazon|goldfire|sleuth|xenu|msnbot|SiteUptime|Slurp|WordPress|ZIBB|ZyBorg|pingdom|bot|yahoo|slurp|java|fetch|spider|url|crawl|oneriot|abby|commentreader|twiceler
